### PR TITLE
[test] Py3 porting

### PR DESCRIPTION
**Pull request by nyov**
Some py3 changes.
Fixed this only enough to make `scrapylib` tests pass for me.
In particular I'm not sure if this should import `to_native_str` from scrapy for `urlpathjoin`.

Can't run the test-suite locally, so someone else with access to the remote scrapinghub endpoints please take over.

### CODE REVIEW

**Comment by nyov** [comment]
@bertinatto, I gathered that. Would be a bit heavy for a single utility function (or three). But it was the quickest way to get the tests to pass :P 
Hope the PR may serve as inspiration to someone else to do better.

This work only happened to get scrapylib tests to pass for now: https://github.com/scrapinghub/scrapylib/pull/71#issue-133766751

**Comment by chekunkov** [comment]
> IMO we shouldn't use scrapy
right

anyways, thanks for the contribution @nyov. Do you want to continue working on this PR or we can use it as a base for further Python 3 porting?

**Comment by nyov** [comment]
Please do use it as a base.. I cannot run the tests locally it seems (as I wrote earlier), so that would be too much shooting in the dark for me :)
Thanks!

**Comment by bertinatto** [comment]
Closing PR because #62 was merged. Thank you, @nyov!

**Comment by nyov** [comment]
Awesome. Thanks for that.

**Pull request closed without merging**
